### ISSUE TITLE
Skipping macro on_cluster_clause while dropping and renaming relations

### ISSUE THREAD

**Issue by d1bevz** [silentsokolov/dbt-clickhouse#10]
Somehow dbt skips on_cluster_clause while renaming and dropping tables

**Comment by d1bevz** [comment]
dbt generates following query:
`drop table if exists db.test__dbt_tmp `
In config I put `'on_cluster="analytics"`

It works fine if it's a table, but when comes to view - it just skips

**Comment by silentsokolov** [comment]
Is it a `snapshot` or a simple case?

**Comment by d1bevz** [comment]
No snapshot, just view

**Comment by silentsokolov** [comment]
I tried reproducing the error and was unable to. Need more information: a example code and output `dbt --debug run`

**Comment by silentsokolov** [comment]
Problem is `dbt` doesn't pass the config to macro other than `create`. I asked the developers a question, waiting answer

**Comment by silentsokolov** [comment]
Ok, it not flexible, but it is solution.

The cluster option move to the profile. Use:

```
your_profile_name:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: [database name]
      host: [db.clickhouse.com]

      # optional
      port: [port]  # default 9000
      user: [user]
      password: [abc123]
      cluster: [cluster name]
```
